### ISSUE TITLE
Convert sqlalchemy from flask sub-install to separate install

### ISSUE THREAD

**Issue by jabrouwer82** [plberg/cs373-idb#15]
I'm confused on how the currect sqlalchemy setup is done. The instructions that Im finding have an entirely different method of doing things.

http://flask.pocoo.org/docs/0.10/patterns/sqlalchemy/

I've installed flask and sqlalchemy machine-wide on the rackspace server, so it should be asimple port, but I want to talk to Parker T about how things are currently done first.

**Comment by phtimmins** [comment]
Do you mean the flask/bin/python copy of python? That's a virtualenv, with flask and sqlalchemy installed. No need to keep them, I just have it that way cause it made the install easier. Also, its using the Flask-squalchemy flask extension described in the link above, which is why you don't see any create_engine or scoped_session calls like in the tutorial. Is that what you mean?

**Comment by jabrouwer82** [comment]
Oops, I skipped right over the flask-sqlalchemy bit.  I've installed all those modules machine-wide (no need for venv), so anyone should be able to clone and run the application from the rackspace server if they like.
